/**
* Created by nghinv on Tue Oct 16 2018
* Copyright (c) 2018 nghinv@luci.vn
*/

// Nơi định nghĩa các types của actions
export const SET_LANGUAGE = "SET_LANGUAGE";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGIN_WITH_FACEBOOK = "LOGIN_WITH_FACEBOOK";
export const LOGIN_WITH_FACEBOOK_SUCCESS = "LOGIN_WITH_FACEBOOK_SUCCESS";
export const LOGIN_WITH_FACEBOOK_FAILED = "LOGIN_WITH_FACEBOOK_FAILED";

export const LOGOUT = "LOGOUT";

export const CHANGE_TYPE_LOGIN = "CHANGE_TYPE_LOGIN";

export const CHANGE_LOCATION = "CHANGE_LOCATION";

// authen
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const GET_ALL_SERVICE = "GET_ALL_SERVICE";
export const GET_ALL_SERVICE_SUCCESS = "GET_ALL_SERVICE_SUCCESS";
export const GET_ALL_SERVICE_FAILED = "GET_ALL_SERVICE_FAILED";

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAILED = "GET_ALL_CATEGORY_FAILED";

export const GET_INFO_USER = "GET_INFO_USER";
export const GET_INFO_USER_SUCCESS = "GET_INFO_USER_SUCCESS";
export const GET_INFO_USER_FAILED = "GET_INFO_USER_FAILED";

export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_FAILED = "UPDATE_USER_INFO_FAILED";

// service request
export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
export const CREATE_SERVICE_REQUEST_SUCCESS = "CREATE_SERVICE_REQUEST_SUCCESS";
export const CREATE_SERVICE_REQUEST_FAILED = "CREATE_SERVICE_REQUEST_FAILED";

// provider service request
export const PROVIDER_SERVICE_REQUEST = "PROVIDER_SERVICE_REQUEST";
export const PROVIDER_LOAD_MORE_SERVICE_REQUEST = "PROVIDER_LOAD_MORE_SERVICE_REQUEST";
export const PROVIDER_SERVICE_REQUEST_SUCCESS = "PROVIDER_SERVICE_REQUEST_SUCCESS";
export const PROVIDER_SERVICE_REQUEST_FAILED = "PROVIDER_SERVICE_REQUEST_FAILED";

export const PROVIDER_RECEIVE_SERVICE_REQUEST = "PROVIDER_RECEIVE_SERVICE_REQUEST";
export const PROVIDER_RECEIVE_SERVICE_REQUEST_SUCCESS = "PROVIDER_RECEIVE_SERVICE_REQUEST_SUCCESS";
export const PROVIDER_RECEIVE_SERVICE_REQUEST_FAILED = "PROVIDER_RECEIVE_SERVICE_REQUEST_FAILED";

export const PROVIDER_REJECT_SERVICE_REQUEST = "PROVIDER_REJECT_SERVICE_REQUEST";
export const PROVIDER_REJECT_SERVICE_REQUEST_SUCCESS = "PROVIDER_REJECT_SERVICE_REQUEST_SUCCESS";
export const PROVIDER_REJECT_SERVICE_REQUEST_FAILED = "PROVIDER_REJECT_SERVICE_REQUEST_FAILED";

export const PROVIDER_SERVICE_REQUEST_HISTORY = "PROVIDER_SERVICE_REQUEST_HISTORY";
export const PROVIDER_LOAD_MORE_SERVICE_REQUEST_HISTORY = "PROVIDER_LOAD_MORE_SERVICE_REQUEST_HISTORY";
export const PROVIDER_SERVICE_REQUEST_HISTORY_SUCCESS = "PROVIDER_SERVICE_REQUEST_HISTORY_SUCCESS";
export const PROVIDER_SERVICE_REQUEST_HISTORY_FAILED = "PROVIDER_SERVICE_REQUEST_HISTORY_FAILED";

// user service
export const USER_SEARCH_SERVICE = "USER_SEARCH_SERVICE";
export const USER_SEARCH_SERVICE_SUCCESS = "USER_SEARCH_SERVICE_SUCCESS";
export const USER_SEARCH_SERVICE_FAILED = "USER_SEARCH_SERVICE_FAILED";

export const USER_SERVICE_REQUEST_HISTORY = "USER_SERVICE_REQUEST_HISTORY";
export const USER_LOAD_MORE_SERVICE_REQUEST_HISTORY = "USER_LOAD_MORE_SERVICE_REQUEST_HISTORY";
export const USER_SERVICE_REQUEST_HISTORY_SUCCESS = "USER_SERVICE_REQUEST_HISTORY_SUCCESS";
export const USER_SERVICE_REQUEST_HISTORY_FAILED = "USER_SERVICE_REQUEST_HISTORY_FAILED";

export const USER_SERVER_REQUESTING = "USER_SERVER_REQUESTING";
export const USER_LOAD_MORE_SERVER_REQUESTING = "USER_LOAD_MORE_SERVER_REQUESTING";
export const USER_SERVER_REQUESTING_SUCCESS = "USER_SERVER_REQUESTING_SUCCESS";
export const USER_SERVER_REQUESTING_FAILED = "USER_SERVER_REQUESTING_FAILED";

export const USER_CANCEL_SERVICE_REQUEST = "USER_CANCEL_SERVICE_REQUEST";
export const USER_CANCEL_SERVICE_REQUEST_SUCCESS = "USER_CANCEL_SERVICE_REQUEST_SUCCESS";
export const USER_CANCEL_SERVICE_REQUEST_FAILED = "USER_CANCEL_SERVICE_REQUEST_FAILED";

export const USER_GET_ALL_DETAIL_PROVIDER = "USER_GET_ALL_DETAIL_PROVIDER";
export const USER_GET_ALL_DETAIL_PROVIDER_SUCCESS = "USER_GET_ALL_DETAIL_PROVIDER_SUCCESS";
export const USER_GET_ALL_DETAIL_PROVIDER_FAILED = "USER_GET_ALL_DETAIL_PROVIDER_FAILED";

// service rating
export const PROVIDER_GET_SERVICE_RATING = "PROVIDER_GET_SERVICE_RATING";
export const PROVIDER_GET_SERVICE_RATING_SUCCESS = "PROVIDER_GET_SERVICE_RATING_SUCCESS";
export const PROVIDER_GET_SERVICE_RATING_FAILED = "PROVIDER_GET_SERVICE_RATING_FAILED";

// get coin
export const GET_COIN = "GET_COIN";
export const GET_COIN_SUCCESS = "GET_COIN_SUCCESS";
export const GET_COIN_FAILED = "GET_COIN_FAILED";

// notification
export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION";
export const LOAD_MORE_ALL_NOTIFICATION = "LOAD_MORE_ALL_NOTIFICATION";
export const GET_ALL_NOTIFICATION_SUCCESS = "GET_ALL_NOTIFICATION_SUCCESS";
export const GET_ALL_NOTIFICATION_FAILED = "GET_ALL_NOTIFICATION_FAILED";

export const CHANGE_PROVIDER_STATUS = "CHANGE_PROVIDER_STATUS";

export const CHANGE_STATE = "CHANGE_STATE";
